name: CI
on:
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        base:
          - 1.15.4-erlang-26.0.2-debian-bookworm-20230612-slim
          - 1.15.4-erlang-25.3.2.2-debian-bookworm-20230612-slim
          - 1.15.4-erlang-24.3.4.9-debian-bookworm-20230612-slim
          - 1.14.5-erlang-26.0.2-debian-bookworm-20230612-slim
          - 1.14.5-erlang-25.3.2.2-debian-bookworm-20230612-slim
          - 1.14.5-erlang-24.3.4.9-debian-bookworm-20230612-slim
          - 1.13.4-erlang-25.3.2.2-debian-bookworm-20230612-slim
          - 1.13.4-erlang-24.3.4.9-debian-bookworm-20230612-slim
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Earthly
        run: earthly --org panda-den --sat idiom-ci --no-output +ci --BASE=${{ matrix.base }}
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
