name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.16.2
          otp-version: 26.2.3

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Run CI
        run: task ci
