name: CI
on:
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.4
            otp: 22.3
          - elixir: 1.12.3
            otp: 23.3
          - elixir: 1.14.5
            otp: 25.3
          - elixir: 1.16.0
            otp: 26.2
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Restore deps and _build cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Run CI
        run: task ci
